version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - analytics-net
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - analytics-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    networks:
      - analytics-net
    depends_on:
      - postgres

networks:
  analytics-net:
    driver: bridge

volumes:
  redis_data:
  postgres_data: